name: Obtiene los items marcados
on:
  pull_request:
    types: [opened,reopened]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobaciones sobre el cuerpo del PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const checklist = /\s*[-\*]\s+\[\s*([xX]?)\s*\]\s+([A-Z]*):?/gm
            let body = context.payload.pull_request.body
            let match = checklist.exec(body)
            while (match != null) {
              let value = match[1] ? true : false
              if ( value === false ) {
                  core.setFailed("⚠️ No has marcado " + match[2] + "\n👉Es importante que sigáis la lista de comprobación en cada entrega" )
              }
            }
      - name: Muestra el resultado
        run: echo ${GITHUB_ENV}
