name: "Tests sobre fuentes del repo"
on: pull_request

jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:
      - name: Comprueba y analiza
        uses: JJ/grading-pr-info-gh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
