name: "Tests sobre fuentes del repo"
on: pull_request

jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:
      - name: Comprueba y analiza
        uses: JJ/grading-pr-info-gh-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Descarga fuente
        uses: actions/checkout@v2
        with:
          repository: ${{env.user}}/${{env.repo}}
          ref: ${{env.rama}}
      - name: Post-check
        run: ls
