name: "Tests sobre fuentes del repo del estudiante"
on:
  pull_request:
    paths:
      - 'proyectos/*.md'

jobs:
  ops-on-pr:
    runs-on: ubuntu-latest
    outputs:
      user: ${{steps.pr_info.outputs.user}}
      repo: ${{steps.pr_info.outputs.repo}}
      file: ${{steps.pr_info.outputs.file}}
    steps:
      - id: pr_info
        name: Comprueba y analiza
        uses: JJ/grading-pr-info-gh-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ops-on-source:
    runs-on: ubuntu-latest
    needs: ops-on-pr
    env:
      user: ${{ needs.ops-on-pr.outputs.user }}
      repo: ${{ needs.ops-on-pr.outputs.repo }}
      file: ${{ needs.ops-on-pr.outputs.file }}
    steps:
      - name: Descarga fuente
        uses: actions/checkout@v2
        with:
          repository: ${{env.user}}/${{env.repo}}
          ref: ${{env.rama}}
      - name: Tests sobre fuentes
        with:
          fase: ${{env.file}}
        uses: JJ/grading-source-tests-gh-action@main
